# Generated by Django 4.2.30 on 2026-05-16 17:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor (R$)')),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('moradia', 'Moradia'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria')),
                ('data', models.DateField(verbose_name='Data')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
